### ISSUE TITLE
[Bug] Guests leave unfinished clothing and even bionics

### ISSUE THREAD

**Issue by frenchiveruti** [OrionFive/Hospitality#121]
Hello, I'm having this issue and yesterday one of the visitors decided to mess up an advanced bionic and it really pissed me off because I didn't get the full material count back.  
The issue is that a visitor starts a job lets say a bionic or a bow or whatever is in my pawns list and then leave it there forever as they leave and never come back.  
It can be solved with areas and that but I don't want to have an area for visitors that limits them that way.

**Comment by OrionFive** [comment]
They do actually come back eventually. You should indeed use areas instead of getting pissed off, since the former solves the problem, while the latter does not.
For every feature 100 people love, there are 3 who hate it. Welcome to the world of working your ass off for free and then getting complaints for it.

**Comment by frenchiveruti** [comment]
I see, yeah I was kind of ranting because visitors working on expensive bionics were kind of annoying, I did eventually deducted that area from the allowed one.  
Thanks Orion. Sorry for making it seem like I was expecting something else.
