### ISSUE TITLE
[Suggestion] Show relation gain when visitors leave (Instead of "Score: X")

### ISSUE THREAD

**Issue by RadGH** [OrionFive/Hospitality#216]
Visitors staying do give a faction relationship bonus. I confirmed this because when visitors left their faction became allies with me. But it's unfortunate that there is no indication of how much relationship one stay gets you. I'm not even sure how much this recent stay gained me:

![image](https://user-images.githubusercontent.com/2008464/52186147-51c92000-27da-11e9-9391-c08e9588c845.png)

That message just gives an (arbitrary?) score. I don't know what the "score" is for, other than calculating if it was a positive/negative stay. I'd suggest a change to show what actual outcome of the stay did for you.

**Current:**
They really enjoyed their stay! (Score: 84) They will visit again in a few days.

**New:**
They really enjoyed their stay! With 84% enjoyment, we gained +9 relationship to a total of 79 (allied). They will visit again in a few days.

(PS: Do they specifically visit again in a few days, or is that just to indicate that they are able to return? If it doesn't specifically queue up the next visit, I would just remove that sentence.)

**Comment by OrionFive** [comment]
Thanks for the indepth report.

It may sound surprising, but it actually used to be like that. Eventually I decided not to show the amount of change anymore since it caused too much aggravation when people felt they didn't get enough or lost too much or it was too easy or not harsh enough. 
A very tiring discussion, especially on Steam where you have to have it over and over again every day (noone reads further than one page of comments). 
Also, when the message is longer, people have trouble parsing it entirely before it disappears. I could send a letter, but that also feels like overkill. 
The score is not arbitrary, though. It's the average of every guest's experience of the stay. This is derived from the mood of the guest when appearing on the map compared to the point when they decide to leave.
The score directly translates to a difference in faction relationship and determines the range of time in which guests visit again. 
If you want to know when that is exactly, you can check their faction on the Comms Console.

**Comment by RadGH** [comment]
Oh I guess I could see that. The bonuses have seemed pretty good to me especially if you compare it to the horrible bonuses when trading ($3000 items sold gives only 1-2 reputation, sigh).

Steam community is super toxic for sure. Lots of children who expect everything for free and haven't had a job to realize how much effort it takes to create and maintain a mod. You've done a great job. Thanks anyway, it was a minor request so no big deal!

**Comment by OrionFive** [comment]
In this case, it's not even that people are toxic, but that I have to explain my choices over and over and over, and either way people are not satisfied. By not showing the numbers the number of people who think it's not satisfactory is just much smaller.
I'm glad you enjoy the mod. I've been working on it for the last 5 years and a lot of my spare time went into it. If I can make someone happy with it it's all the more worth the while.
