### ISSUE TITLE
[Suggestion] Visitor group size based on available visitor beds

### ISSUE THREAD

**Issue by RadGH** [OrionFive/Hospitality#217]
I noticed some steam comments about group size being too large. There is an option to change that and an alert to keep visitors away until you have guest beds. Both good solutions.

But what if there were another option to automatically change the group size to the number of beds? I just realized I had my group size set to 4 from a long time ago and I forgot the setting existed. I forgot it was a setting. I had 16 beds and was disappointed when small groups kept joining.

Now I changed that setting, it's fixed for now.

But I think it would be a great idea if you could enable a checkbox that makes maximum group size match your number of visitor beds (and of course double beds could count as 2). If you don't have any visitor beds it could just default to the current value, and then if you choose to dismiss visitors until you have beds, even better.

**Comment by OrionFive** [comment]
Thanks for the suggestion.
It would go fine until two groups arrive at once and then it'll be complaints again. The harsh reality is that it's just not possible to make it right for everyone.
Not even with options that make it customizable. So in the end the decision comes down to whether I think it's worth my time to change something or not.
Anything I change comes with an often heavy backlash of people who liked it better before, don't get it or want even more. Also every change usually comes with days of bugfixing because suddenly some obscure mod has become incompatible. So in order to not completely lose my motivation I try to focus on the people who enjoy the changes and how it already is. But this also means that I will only implement things that I think have a much higher potential for gain than loss.
Don't let this discourage you from suggesting changes. I do think this is a nice solution, but I also think it won't work well enough to fix the issue.

**Comment by RadGH** [comment]
No problem, I didn't consider multiple groups either so I can see that being an issue or at the very least an unnecessary complication.

**Comment by OrionFive** [comment]
Btw, many many thanks for your donation. I can't carve out much time for modding and since I don't play RimWorld anymore it has become unpaid work. Contributions like yours help me keep going.
