### ISSUE TITLE
Mod interfering with Hospitality

### ISSUE THREAD

**Issue by maureenx1138** [OrionFive/Hospitality#271]
Hi,

I have a lot of mods (238) and I know one I recently installed is interfering with your Mod.  I don't expect you to troubleshoot all my mods but if you could maybe point me in the right direction as to which mod might be causing the issue I would greatly appreciate it.

As soon as the game loads, I get the error in the screenshot and in the mod settings, the option for the maximum group size just is not there.  In the game, no visitors come.

Thanks for any help you can give.

Screenshot:
![Hospitality error](https://user-images.githubusercontent.com/53801637/62504412-f8a86c00-b7bd-11e9-816d-5e214909c288.JPG)

My Logs:
https://gist.github.com/1ed2a8fb56298eba963713b8d0fe6d3f

**Comment by OrionFive** [comment]
Unfortunately, I see this error regularly. It seems like it's caused by a corrupted mod config file. 
You have to find the RimWorld folder in your %appdata% and rename or delete the mod config file to reset it.
I assume it's an issue of HugsLib, not handling uninitialized settings correctly, but I'm not sure. 

Please let me know if this helped.

**Comment by maureenx1138** [comment]
It appears to have worked!  I am not getting the error, all the options are present and I have guests :)

Thank you so much for taking the time to make this great mod, and help people like me!!!

**Comment by OrionFive** [comment]
No problem, thanks for using my mod!
If you really enjoy it, please consider [becoming a sponsor](https://www.patreon.com/orionmods) :)
