### ISSUE TITLE
Guests should rate their stay by taking "opinion samples" every x hours

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#280]
Currently, the rating of a guest is the difference between his mood when he came and when he left, offset by a difficulty modifier based on how well the player is established.

This new system I propose would take snapshots every x hours of the guest's mood. 
At the end of the guest's stay, his opinion of the stay will be the average of all snapshots, maybe with a weighed bias towards the end of the stay, to not factor in arrival-unhappiness too much.

The upside of this system is that it's not completely dependent on the final mood of the guest. The downside is that the guest being unhappy in between or at the beginning will pull down the score.

Please discuss.

**Comment by lbmaian** [comment]
Sounds promising. An alternative approach to calculating "score" is to have those individual opinions you listed just apply scalable mood (de)buffs. That way, technically speaking, the mood is still what matters in the end, and for better or worse, you can still get the same consequences for poor mood.

**Comment by OrionFive** [comment]
That would indeed be more in line with how RimWorld already works... and the factors I've mentioned are practically in there already.
What bothers me, though, is that in the current system it's all fine, as long as the guest is happy at the very end. And if they arrive too happy you'll have a hard time pleasing them. I could just take samples of their mood, though, but then I still have the issue that I can't tell just from the mood if the player did a good job or not.
I often hear players who are puzzled why the guests didn't like it, or _did_ like it, even though they slept in the barn.

**Comment by lbmaian** [comment]
Ah I see. Then yeah having a separate score does make sense, though the mood (de)buffs should still remain.

Hmm, how about rather than taking snapshots of the current mood level, you take them of the current level that mood is trending towards (`mood.CurInstantLevel` I think)?

How are you going to show the score though? Or the aggregate, recently-weighted score?

**Comment by OrionFive** [comment]
Yeah, I would definitely use CurInstantLevel. It makes a lot more sense than the sliding mood value.
I suppose I should show a "current score" value and a "total score" value. The total is just what the score would be if the guest left right now. I suppose players can game this by sending guests away at the perfect moment, but guests' initial low score would discourage that.

As a later expansion, I could add a tooltip to the current score that breaks it down into the score components.

**Comment by lbmaian** [comment]
Showing two score columns along with mood column would probably be confusing. "Total score" is also somewhat misleading in naming. Maybe you could have something similar to mood, where you have an CurInstantLevel and a CurLevel, but instead of the Need_Seeker behavior, the CurLevel would be computed as that recent-weighted average. Then you can just show the current (weighted average) score in the column, and players can just look up the needs tab for details. Bonus points if little arrows are shown on column entries that show the direction that the levels are trending.

Or maybe just changing from mood.CurLevel to mood.CurInstantLevel for score purposes is enough of a stopgap.

**Comment by OrionFive** [comment]
Hm. Yeah, a single number would be better, I suppose. I'll see what I can do.

**Comment by OrionFive** [comment]
I'm starting to think this sampling idea is not an improvement. I'll scrap it for now.
