### ISSUE TITLE
Hospitality: Toggle button for keeping guests longer during raids

### ISSUE THREAD

**Issue by zeuznova** [OrionFive/Hospitality#313]
Hello i have this idea.
Note: I am not a native English speaker some syntax may or will be strange.
   
Some times the guest are leaving or leave during raids in this case i propose while they are in home  area they stay a little longer and if they are outside of home area they flee and don't wait those that are behind to left the area or fight the raiders and all die.
this can be done by a button in the guest(where you configure the shopping area and entertain guest and make default the configuration) .

Not all the guest will be save but we can try save the most.

Thanks.

**Comment by OrionFive** [comment]
Making their travel behavior work is actually quite tricky, because changing it breaks backwards compatibility (and thus people's save games).

So I propose a different solution: A menu where the player can specify which direction to the base is save. Guests will always arrive from and leave to that direction. 
The player will have to think of keeping it updated when raids appear, though 
So that's probably annoying. Also guests will always come from that direction then.

**Comment by zeuznova** [comment]
That may work. but make the guest stay a little longer helps to, in my game the raid was so big and take me some time to finish, and the guest leave and enter in battle...
Ok then.
Making the guest flee like when a raid lose is hard no problem, next is when you save a guest it stay a little longer can't make a variation of this like i said the raid is in the door and the guest walk to their doom.

thanks

**Comment by OrionFive** [comment]
The problem here is that I can't tell if a raid is going on or there are just some hostiles somewhere on the map.

I could add a button to tell guests to stay longer. But this can probably be abused. Although I don't know yet how. 
I could give the guests a debuff when they want to leave but are told they can't.

**Comment by zeuznova** [comment]
Or pay reputation or money or both, for the forced stay.

**Comment by OrionFive** [comment]
Maybe the debuff can increase over time. So eventually you'll have to deal with mental break cases everywhere.

**Comment by zeuznova** [comment]
That sound good and interesting... i like the idea.

**Comment by ttr** [comment]
Hey,
Apologies for commenting on old thread.

To prevent abuse, what about this scenario - You can "ask them to stay" for 1 more day,
1st time you will use, it will cause small negative buff like -5 and "forced to stay in"
2nd time (to same group), will cause some sort of unrest like another -20 and "feeling like prisoner" 
each next time would trigger:
- hostile action of whole group towards colony
- decrease relations between colonies
So for raid scenario, stopping them for a day would be almost no harm.

However, in case of serious environmental issue that will last longer than 24h (eg cold snap), those colonists would no exit map cleanly - if there is chance of detecting those, this could add some options, like:
- they will stay longer w/o any penalty
- they will stay for a fee / favor (so colony needs to pay them some silver per each day OR colony will have some task to full fill when they will live, like deliver some goods, raid other camp, etc)
- they will take a chance and if they will fail they will blame colony obviously
This would help player to control guests more but not with out potential downsides.

Anyway, just small 2c form my side.

**Comment by OrionFive** [comment]
That's all nice, but a lot of work. All those special cases have be implemented and communicated to the player.
So it's much easier to just use existing debuff mechanism and make it worse over time.

**Comment by OrionFive** [comment]
I noticed I have another item for this issue (#470), so I'm going to close this one.
