### ISSUE TITLE
Add a guest-arrival spot

### ISSUE THREAD

**Issue by emipa606** [OrionFive/Hospitality#413]
I have an issue where the guest area includes some locked rooms. Sometimes guest groups just leaves the map since they cannot walk to the ”chillspot” assigned in the code. 
If Im not using the hospitality-mod the  [Trading Spot-mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658) modifies the arrival toil for guests to use the trading-spot as arrival point but if hospitality is loaded it skips that. I assume that is because the toil is no longer VisitColony. 

Would it be possible for Hospitality to add its own arrival spot to make it possible to define where the guests will walk to when they enter the map?

**Comment by OrionFive** [comment]
I'm actually hoping that I can find a better way for them to arrive. The arrival spot causes me a lot of headache. Any ideas are welcome. 
But I also think the player shouldn't be required to place a marker. It doesn't really make sense, because after the initial pathfinding check it wouldn't be used anyway.

**Comment by emipa606** [comment]
Yes, ive followed the earlier discussions on the topic. I agree that it would be nice to skip the spot. I was thinking that the spot would be an extra, like if it exists use it, otherwise use the standard logic. 
Another way would be an option to turn off the logic all together, just have the "chill-spot" be the same as the spot they enter the map on and then leave them to their own pathfinding.

**Comment by OrionFive** [comment]
I would go for the latter, but the reason they have the spot is so a check can be made if they can actually reach the base.
For a perfect check, I'd have to test every spot in their assigned area until a reachable one is found. But this can be ridiculously expensive, especially if the base is actually not reachable from where they are. So that's not really an option. 
If I'm not mistaken, it's currently testing a couple of spots. But somehow locks mess with that and make the paths all fail. 
It's very hard to reproduce and test because it only happens sometimes.

**Comment by emipa606** [comment]
I have a pretty reliable way of reproducing it. An enclosed base, guest area covers base and a few tiles outside and then lock the door for visitors. 
The trouble is that the check for reachability uses the generic function that assumes that the guests can walk through all doors. 
There is a reachability-function that the normal pathfinding uses but that requires a pawn to check with. Worst case you could spawn a guest-pawn, use it to chech reachability for the group and then despawn it.

**Comment by OrionFive** [comment]
Hm... But assuming they can pass all doors should be fine. It sounds to me like locked doors don't let the generic check pass at all. Or is that what you meant?
Sounds to me like the locks mod violates the "pass through doors" path check assumption by blocking anyway.

**Comment by emipa606** [comment]
I think its the TraverseMode that can be set to ByPawn instead of PassDoors if you use the FindPath-function with a guest-pawn. 

As for the spots to test perhaps first test guest-bed cells. I think you can assume that anyone using this mod would have built some guest-bed. :)

**Comment by OrionFive** [comment]
Yeah, I changed to code to use a guest pawn now, to find valid spots. But I definitely can't assume the presence of beds. You'd be surprised how people play 🙄
But anyway, it should work much better now. Have you tried the version I uploaded yesterday yet?

**Comment by emipa606** [comment]
Ill try it tonight. About the guestbeds, I just thought it would be a good idea to try those spots first and then do the random-spots if there are no beds or if they fail the path check. Just to make things more efficient. But as long as it works Im happy 😃 
Ill get back to you when ive tested it!

**Comment by emipa606** [comment]
Seems to be working as intended, the guests happily finds their area even with most of the base locked of.
I started getting an error `Alien Framework does not have a method 'CanEat'.` though but I left a comment at the relevant code-checkin where I think it might have gone wrong.

**Comment by OrionFive** [comment]
Thanks. Must have missed that!
