### ISSUE TITLE
Gastronomy: RimWorld Children incompatible?

### ISSUE THREAD

**Issue by jmpatag** [OrionFive/Hospitality#480]
**Describe the bug**
i dont know it just happen just want to share it here
**To Reproduce**
im sorry i really dont know

**Console log**
https://gist.github.com/613dd7ae82b3204fd1e11d4ac73c1497

**Comment by OrionFive** [comment]
As far as I can tell, the problem is RimWorld Children. It's either broken, wrongly installed, or conflicts with another mod.
It might be only one of multiple issues in your modlist, though.

Please reopen this issue if you can provide more information or have resolved the RimWorld Children problem.
