### ISSUE TITLE
Gastronomy: Colonist will not order, waiter wont wait

### ISSUE THREAD

**Issue by RubyFlareon** [OrionFive/Hospitality#481]
**Describe the bug**
Colonist just does this: Standing. Queued: Consuming Dining spot... or something like that. The waiter doesn't do anything, because the colonist isn't ordering.

**To Reproduce**
1. Just wait for them to go to the dining table.
2. That's it!

**Console log**
https://gist.github.com/a28c06cf4496f9163f3c74a641cd35d2

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
i... i dont know how
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.
![20201110124527_1](https://user-images.githubusercontent.com/74267743/98726503-d784e280-2353-11eb-8812-a523b63ed1a8.jpg)

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
There's a whole range of problems in your mod list. For one, "They're In The Trees" is causing an exception, and "Meat Shield Mod" as well. Also "MOARANDROIDS" and "Colonists Deco".
This is probably just the tip of the iceberg (the worst offenders). Given that so many mods are wreaking havoc in your game, it's not strange that Gastronomy displays symptoms.

Note that if you remove mods during a playthrough, it will break your savegame. So if you decide to remove the problematic mods, you will have to start over.

I'm afraid I can't help you here since this is not a Gastronomy issue. If you have more questions or improved your configuration, feel free to reopen this issue.
