### ISSUE TITLE
Gastronomy: CTD on Linux

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#482]
Test this (reported on Steam comments)

**Comment by TBleader** [comment]
Hey, I'm the one who reported this on steam. Turns out the issue isn't with Prepare Carefully, at least I think it isn't since it occurs even when only Gastronomy is loaded.  In these scenarios I only had Harmony, Core, Royalty, HugsLibs, and Gastronomy loaded. The steps I took were:
New Colony -> Next selecting default Crashlanded scenario -> Peaceful, Reload Anytime on default storyteller  then hitting next -> Generate (sometimes got CTD here) -> random starting position -> next -> start (if it didn't crash earlier, it would crash here during Generate Map).

Log 1004 was the crash on generate planet, 2, 3, and 5 were the crash on generate map. Log 1000 is the same as I first reported, just included so they were all in the same place. During 5, the first generate planet seemed to fail? After I hit generate planet the window went away as if to switch to the planet view, but then the window returned with a new random seed and no planet was generated. It let me generate that second time, and then crashed during map generation.

With Prepare Carefully it instead crashed if I would use the Prepare Carefully button. It also would crash sometimes when generating the planet, and then if I don't use Prepare Carefully button and it didn't crash generating the planet, it would crash generating the map. 1006 is a log from where I didn't press the Prepare Carefully button, it didn't crash on generating the planet, but rather crashed when generating the map. It appears to be the same error as 2, 3, and 5.

I have verified game files, unsubscribed and resubscribed, deleted local mod copy and resubscribed, restarted steam, etc. 

Upon removing Gastronomy, the issue disappears. I was able to run a game for 10 minutes on fastest speed without issues. (I didn't go further as it wasn't an attempt to play, rather a check if the game would experience a crash within the first few days).

I'm.. Not sure what causes this if I am being honest. Maybe is some incompatibility with Linux that doesn't represent itself on windows? I imagine most users are on windows so it might explain why they didn't have any issues.
Here is my system info in case it helps:
`OS: Arch Linux x86_64`
`Kernel: 5.9.4-arch1-1` 
`CPU: Intel i7-8700K (12) @ 4.700GHz`
`GPU: NVIDIA GeForce GTX 1080 (nvidia 455.38-3)`
`Memory: 12573MiB / 31975MiB `


[rimworld_logs.zip](https://github.com/OrionFive/Hospitality/files/5527674/rimworld_logs.zip)

**Comment by OrionFive** [comment]
I've found this: https://github.com/pardeike/Harmony/issues/343
Apparently, there are various problems that can occur on Linux only.

**Comment by OrionFive** [comment]
There's also this: https://ludeon.com/forums/index.php?topic=37241.45

**Comment by OrionFive** [comment]
I'm sorry, but I don't have more time to look into this 😦

**Comment by simplyWiri** [comment]
The linux harmony issue can be solved with [Harmony Fix For Penguins](https://steamcommunity.com/sharedfiles/filedetails/?id=2149016328)

If this does not solve your issue - The issue is elsewhere.

@TBleader

**Comment by OrionFive** [comment]
Thanks, @simplyWiri, I hope this resolves this issue. Please reopen, if it persists.
