### ISSUE TITLE
Hospitality: I cannot make beds for guests

### ISSUE THREAD

**Issue by Gekokeitaro** [OrionFive/Hospitality#499]
When i select any normal bed, i cannot set it "for guests". The button for that appears and it's interactable, but it simply don't change it's state when clicked.

**To Reproduce**
1. Select a normal bed
2. Click on "for guests"
3. Nothing happens

**Console log**
https://gist.github.com/0879926ec81e745e99b95bf5b698681c

**Comment by OrionFive** [comment]
Looking at your log it says that beds are missing a component. This is due to another mod removing them.

A potentially problematic mod is Interests Framework, since it crashes during initialization. Beyond that it's pure guessing and removing mod by trial and error until the message disappears, that beds are not initialized for Hospitality.

**Comment by Gekokeitaro** [comment]
D'oh, it makes so much sense xD. Sorry, i don't know how i didn't come up with that before \*facepalm\*

I will take a look at IF and the rest of the modlist to see if i find the problem, thanks for the quick response <3

**Comment by OrionFive** [comment]
Okay, since more and more people seem to have this issue, I'm trying to find out which mod specifically is messing with ma beds. Here's a list of all mods everyone with the problem has in common. If I can get more people to share their logs, I can maybe narrow it down further ([using this tool](http://www.molbiotools.com/listcompare.html)).

- Call of Cthulhu - Elder Things (Continued)(Mlie.CallofCthulhuElderThings)[mv:1.0.2.0]: ElderThingFaction(1.17.0.1)
- Call of Cthulhu - Factions (Continued)(Mlie.CallofCthulhuFactions)[mv:1.0.1.0]: CthulhuFactions(1.18.0)
- Core(Ludeon.RimWorld): (no assemblies)
- EdB Prepare Carefully(EdB.PrepareCarefully)[mv:1.2.1]: 0Harmony(2.0.2), EdBPrepareCarefully(av:1.1.1,fv:1.2.1)
- Fluffy Breakdowns(fluffy.fluffybreakdowns)[mv:4.4.54]: Fluffy_Breakdowns(av:4.0.0,fv:4.4.54)
- Gastronomy(Orion.Gastronomy)[mv:1.2.4]: Gastronomy(av:1.0.0,fv:1.2.4)
- Gunplay(automatic.gunplay): 0Harmony(2.0.2), Gunplay(1.0.379.18)
- Humanoid Alien Races 2.0(erdelf.HumanoidAlienRaces): 0Harmony(2.0.2), AlienRace(1.0.0)
- Interaction Bubbles(Jaxe.Bubbles): Bubbles(1.6.2)
- Mad Skills(ratys.madskills)[mv:2.4.0.0]: 0Harmony(av:2.0.2,fv:1.2.0.1), MadSkills(1.0.0)
- Realistic Rooms(crlsniper.realisticrooms): (no assemblies)
- Rim of Madness - Vampires(Kato.Rimofmadness.Vampires)[mv:1.22.0.1]: 0Harmony(2.0.2), Vampire(1.18.0)
- Rim of Madness - Werewolves (Continued)(Mlie.RimofMadnessWerewolves)[mv:1.0.4.0]: Werewolf(1.18.0)
- RunAndGun(roolo.RunAndGun)[ov:2.0.1]: RunAndGun(av:2.0.0,fv:2.0.0)
- Simple sidearms(PeteTimesSix.SimpleSidearms): SimpleSidearms(1.4.5)
- Vanilla Animals Expanded — Arid Shrubland(VanillaExpanded.VAEAS)[mv:1.1.0]: 0Harmony(av:2.0.2,fv:2.0.0.7), VAEShrubland(1.0.0)
- Vanilla Animals Expanded — Desert(VanillaExpanded.VAED)[mv:1.0.0]: (no assemblies)
- Vanilla Animals Expanded — Extreme Desert(VanillaExpanded.VAEED)[mv:1.0.0]: (no assemblies)
- Vanilla Animals Expanded — Temperate Forest(VanillaExpanded.VAETF): NocturnalAnimals(1.0.0), VAEShrubland(1.0.0)
- Vanilla Apparel Expanded(VanillaExpanded.VAPPE)[mv:1.2.0]: (no assemblies)
- Vanilla Armour Expanded(VanillaExpanded.VARME)[mv:1.2.0]: 0Harmony(av:2.0.2,fv:2.0.0.7), AdvancedShieldBelts(1.0.0), Camouflage(1.0.0)
- Vanilla Events Expanded(VanillaExpanded.VEE)[mv:1.1.0]: 0Harmony(av:2.0.2,fv:2.0.0.7), VEE(1.0.0)
- Vanilla Expanded Framework(OskarPotocki.VanillaFactionsExpanded.Core): VanillaStorytellersExpanded(1.0.0), VFECore(av:1.1.7,fv:1.1.9)
- Vanilla Factions Expanded - Settlers(OskarPotocki.VanillaFactionsExpanded.SettlersModule)[mv:1.1.0.0]: VFE_Settlers(1.0.0), VanillaFactionsExpandedSettlers(1.0.0 [no FileVersionInfo])
- Vanilla Furniture Expanded - Farming(VanillaExpanded.VFEFarming)[mv:1.0.1.0]: 0Harmony(av:2.0.2,fv:2.0.0.7), VFEF(1.0.0)
- Vanilla Furniture Expanded - Medical Module(VanillaExpanded.VFEMedical)[mv:1.1.0]: 0Harmony(av:2.0.2,fv:2.0.0.7), AOMoreMedical(1.0.0)
- Vanilla Furniture Expanded - Production(VanillaExpanded.VFEProduction)[mv:1.0.3.0]: 0Harmony(av:2.0.2,fv:2.0.0.7), VFEProduction(1.0.0)
- Vanilla Furniture Expanded - Security(VanillaExpanded.VFESecurity)[mv:1.1.1.0]: ExplosiveTrailsEffect(1.0.7140.31563), NoCamShakeExplosions(1.0.0), VFESecurity(1.1.2.2)
- Vanilla Furniture Expanded(VanillaExpanded.VFECore)[mv:1.1.0]: 0Harmony(av:2.0.2,fv:2.0.0.7), AOMoreFurniture(1.0.0)
- Vanilla Hair Expanded(VanillaExpanded.VHE)[mv:1.0.3]: 0Harmony(av:2.0.2,fv:2.0.0.7), VanillaHairExpanded(1.2.0)
- Vanilla Traits Expanded(VanillaExpanded.VanillaTraitsExpanded): 0Harmony(2.0.2), VanillaTraitsExpanded(1.0.0)
- Wall Light(Murmur.WallLight): WallLight(1.0.0)

**Comment by Gekokeitaro** [comment]
Hi Orion,

I revised my modlist and solve some conflicts. After reinstaling by batches i realized that Rim of Madness - Vampires make a conflict with sleeping spot.

Aside of that, by reordering with rimpy and making sure that Hospitality is at bottom i've seen that it works with no problem except the sleeping spot. I hope this help you and mod's users ;)

**Comment by OrionFive** [comment]
From Steam discussion:

```
It looks like that Call of Cthulhu - Elder Things (Continued) causes the issue.

It includes PatchOperationReplace patch which replaces CompAssignableToPawn_Bed compClass with ElderThingFaction.CompAssignableToElder and I suppose Hospitality uses "CompAssignableToPawn_Bed " to decide whether to generate "For guests" variant for the bed.

The result is this warning:
Not creating guest beds for sleeping spot from Core. It does not have a CompAssignableToPawn_Bed.
```
I can fix this problem from Hospitality's end.

**Comment by OrionFive** [comment]
Fixed for next version.
