### ISSUE TITLE
Invalid job count (-1) error when guest tries to buy item

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#5]
When a guests tries to buy an item, Toils_Haul.ErrorCheckForCarry shows an error, because apparently the job count is -1, while it should be 1.

**Comment by CallMeOzz** [comment]
confirmed, although it doesn't appear to block the sale; the value of Count is reset to 1, and the sale appears to complete.

Is the call to ErrorCheckForCarry no longer needed, or has the default value for Count changed?

I'm probably just missing something obvious, but I was having trouble understanding the purpose of the Count proprty on the curJobs object, since it isn't a collection of any kind...

**Comment by OrionFive** [comment]
The sale works okay, yes. ErrorCheckForCarry fixes the job count, so it is necessary. But it would be better if the job count was correct to begin with. There must be a reason it throws an error.

**Comment by OrionFive** [comment]
You were right. The check is not necessary. I've tested without the check and it seems to work well. I've left the check for 0 jobs in.
