### ISSUE TITLE
Hospitality: Allow guests to attend gatherings

### ISSUE THREAD

**Issue by emipa606** [OrionFive/Hospitality#512]
**What problem does your suggestion solve**
There are mods that use the gathering-hook for events. (Razzle Dazzle for example)
If it were possible to allow (by setting) guests to use the Party-hook they should be able to join in these events.

**Describe the solution you propose**
I think it should be possible by adding it to the relax-dutydef

**Describe alternatives you've considered**
I assume it would be possible to add as patch in each mod as well.

**Comment by emipa606** [comment]
Sorry if its a duplicate of
https://github.com/OrionFive/Hospitality/issues/434#issue-651282235

**Comment by OrionFive** [comment]
Last time I checked I couldn't find a proper solution, since parties use the lord system, but visitor groups do so as well - so it's one or the other. The solution in #434 is faking party behavior to give the impression that it works the same way. But this involves more work than just using the hook.
