### ISSUE TITLE
Mod name: Name of the problem

### ISSUE THREAD

**Issue by Mystalic1** [OrionFive/Hospitality#514]
**Describe the bug**
The Problem is that every time my dudes should clean or haul automatically, they dont do it and the log file opens with the report thats on 759. If i deactivate hospitality and load the same save file i cant even haul or clean manually. A new game without hospitality and everything is fine. It could be another mod that makes the problem but i tried a lot of de- and activating and nothing helps. maybe you have an idea.

**To Reproduce**
I Load the game and if someone didnt need to do something and should haul or clean they dont do it and the console pops up.

**Console log**
https://gist.github.com/HugsLibRecordKeeper/905e4745b93e0b84af047a725e799959#file-output_log-txt

**Error stacktrace**
I did activate that guest cant help but nothing changed. also i remember that i deactivated following mods:
OskarPotocki.VFE.Insectoid
fluffy.blueprints
CodeOptimist.JobsOfOpportunity
Sandy.RPGStyleInventory
avilmask.CommonSense
Oblitus.AnimalsLogic
fluffy.backuppower
Atlas.AndroidTiers
Roskii.Astoriel
Kerevan.OttoDrow
shauaputa.pawnboldrace

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
Well, deactivating mods midgame is not supported by RimWorld and doesn't solve anything. But it does break things further, usually. The error indicates a possible conflict between Hospitality and VFE Mechanoids. But it could also be circumstantial. Like for example you've deactivated a mod before in the same save file. On 1/19/21, 23:39 Mystalic1 <notifications@github.com> wrote:

   
  Describe the bug The Problem is that every time my dudes should clean or haul automatically, they dont do it and the log file opens with the report thats on 759. If i deactivate hospitality and load the same save file i cant even haul or clean manually. A new game without hospitality and everything is fine. It could be another mod that makes the problem but i tried a lot of de- and activating and nothing helps. maybe you have an idea. 
  To Reproduce I Load the game and if someone didnt need to do something and should haul or clean they dont do it and the console pops up. 
  Console log https://gist.github.com/HugsLibRecordKeeper/905e4745b93e0b84af047a725e799959#file-output_log-txt 
  Error stacktrace I did activate that guest cant help but nothing changed. also i remember that i deactivated following mods: OskarPotocki.VFE.Insectoid fluffy.blueprints CodeOptimist.JobsOfOpportunity Sandy.RPGStyleInventory avilmask.CommonSense Oblitus.AnimalsLogic fluffy.backuppower Atlas.AndroidTiers Roskii.Astoriel Kerevan.OttoDrow shauaputa.pawnboldrace 
  Fixing bugs takes a lot of time. Please consider becoming a patron to support development.

**Comment by Mystalic1** [comment]
Omg i found the problem right now. it has nothing to do with hospitality so sorry about that. after i deactivate the mod "Combat Training" everything works fine even with the loadet midgame :D so happy right now that i dont need to start over.

**Comment by OrionFive** [comment]
Ah, great!On 1/20/21, 12:26 Mystalic1 <notifications@github.com> wrote:

   
  Omg i found the problem right now. it has nothing to do with hospitality so sorry about that. after i deactivate the mod "Combat Training" everything works fine even with the loadet midgame :D so happy right now that i dont need to start over.
