### ISSUE TITLE
Bug while recruiting guests

### ISSUE THREAD

**Issue by Pomerinke** [OrionFive/Hospitality#52]
Tried to recruit a visitor. Received the "new recruit" notif 3 times, but still didn't have him recruited. The visiting group was maybe 5-6 people. All except for one ended up in restraints and left, including the one I had tried to recruit. 

Realized after the fact that one was still hanging around.

**Comment by OrionFive** [comment]
Sorry for making you jump through all the hoops. I still need your output_log.txt, from when I happened (or when it happens again). Can't do much otherwise.

**Comment by Pomerinke** [comment]
Next time I get the error, I'll share it as you requested. I haven't seen it since, but I changed my autosave settings from every day to 14 days.

**Comment by OrionFive** [comment]
I have possibly received a (useful) error log for this bug:
https://gist.github.com/HugsLibRecordKeeper/61298f380fd9ce8d39d450cab60a4ba0

I'll see when I get around to fix it.

**Comment by OrionFive** [comment]
Gah. I had this fixed days ago already, but hadn't released the fix. Next version it should be fine again.

**Comment by Pomerinke** [comment]
Finally ended up getting a new error. I browsed through it briefly and I don't think my original problem was directly linked to your mod. 
Here's the link in case you want to check it out yourself: https://gist.github.com/Pomerinke/6fc581ccb0d69790df25613b87afc475

**Comment by OrionFive** [comment]
Hmm. I think you have to be at PawnPrioritiesTracker with this one...

**Comment by ultimatedelman** [comment]
Sorry to necro this issue, but I just got this. Here's my gist (just search for "recruit" and you'll see the errors): https://gist.github.com/867fac186095ab5affd6c20e221a289b

I hit the recruit button a bunch of times so that's likely why it's appearing so much. I then tried to rearrange the mods and put hospitality last, same issue.

I think I did pay the -30 recruitment goodwill cost, the guy just won't join my colony. But yea, hit the "Recruit" button in the Guest tab, confirmed that I wanted the pawn, new recruit blue square notif came down, pawn is not in my faction list/part of my colony.

**Comment by OrionFive** [comment]
Thanks for reporting this. It should be fixed in the next version. It's probably caused by a mod conflict, since the guest group has to have odd members that miss needs, thoughts or something else.
I'm not sure yet when I will upload the next version, though, but if you're in a hurry, you can just download the current repository (not the latest release).

**Comment by ultimatedelman** [comment]
No problem! Thanks for making this mod, it's great! I'm not in any hurry. I missed out on that guy but so what. I was able to successfully recruit a pawn a little bit later, so it's not completely broken. I will patiently wait for your next release!

**Comment by OrionFive** [comment]
Sorry for the trouble!
