### ISSUE TITLE
Minor Incompatibility with CE ; Can order guests to empty their inventory

### ISSUE THREAD

**Issue by Valerate** [OrionFive/Hospitality#56]
Hi

I'm doing playtesting with NIA's new CE and I noticed that I could open Guests inventory and drop their items. I mentioned this for NIA and he said that this was a Hospitality issue. So here I am :)

https://github.com/NoImageAvailable/CombatExtended/issues/171

http://imgur.com/a/tyEcY

**Comment by OrionFive** [comment]
Yeah this is an issue that keeps coming back and I don't know yet how to fix it.

**Comment by Valerate** [comment]
I noticed that when the guests entered the map, I couldn't order them to drop their items, but somewhere along their way to my base I suddenly started to be able to.

**Comment by OrionFive** [comment]
Hm. That's quite interesting. Maybe that's where it slipped through.

**Comment by NoImageAvailable** [comment]
So after revisiting this it looks like now that the bug was fixed in Hospitality proper this is an actual problem. My first guess is if the fix required changes to the gear tab then they don't carry through the CE version since it's using a custom tab instead.

**Comment by NoImageAvailable** [comment]
So it looks like [this bit of copy-paste code](https://github.com/NoImageAvailable/CombatExtended/blob/master/Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs#L195) was not up-to-date with vanilla, which has since fixed this issue by changing the check for `SelPawnForGear.HostFaction == Faction.OfPlayer` to `SelPawnForGear.IsPrisonerOfColony`. Updating the CE code seems to have fixed the issue, will test to confirm and include the fix in the next CE release.

On a side note, this should also make this mod's Harmony patch to ITab_Pawn_Gear obsolete as the button should no longer show on guests at all.

**Comment by OrionFive** [comment]
Awesome, @NoImageAvailable! Can you already confirm that it's fixed?

**Comment by NoImageAvailable** [comment]
So far no problems in testing. The fix will be in the next CE release whenever I can get around to fixing the other stuff I was working on there.
