### ISSUE TITLE
Hospitality: Single rooms should be more attractive than barracks

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#583]
Apparently, bed quality factors in a bit too much. Also double check if single room attractiveness isn't broken.

**Comment by christophkogler** [comment]
I think it is because barracks are larger rooms with many beds, leading to a high impressiveness rating that can drive up its score ( BedUtility.cs, BedValue() ) to guests. 

Bed quality drives up the score in two ways, by increasing it's comfort and by directly increasing quality. For example, I have a legendary wooden double bed that should be adding 128 to the score via comfort (1.28*100) and then another 125 via its quality ( (legendary=7-2)*25 ), which should make it almost 125 final attractiveness alone - over half, in my room's case. Most of the vanilla impressiveness of the room itself is from the bed too, because it's both worth half of the rooms value and beautiful because it's legendary. 

Based on me doing the math from the code myself, for the room I have, it looks like single room attractiveness is working correctly. The 180 extra score (if that is what you mean by the sentence) is applied.

A big barracks with an impressiveness-based score of 150 vs a bedroom with 75 score plus the 180 single bed room bonus (255) could be easily decided by the bed alone. If the barracks has a legendary and the bedroom has an awful, there is a total of around 300 score or 150 final attractiveness difference based on quality differences. The barracks with a legendary would have about 450 score vs the bedroom with 200.

I actually think bed quality should be a massively important thing for the value of a room. I personally would be much happier in a bad room resting on an incredible bed than a gorgeous room in a bad bed. If the barracks had a memory foam mattress and the luxuriant single room had a couple of wooden planks on a frame, I'd probably want to sleep in the barracks.

For balancing purposes, could increase the bonus from being a single bed room some, or multiply the vanilla impressive rating by some factor before adding it in for barracks. So the big 150 impressiveness barracks is only 75 score, instead of 150. Would only require a check in GetRoomImpressiveness for if it is a barracks, and then a multiplication? Small single bed rooms with at least okay beds will be more attractive than most barracks, then.

**Comment by OrionFive** [comment]
Thanks for looking into this!So what you're saying is that the formula works correctly and doesn't need changing?

**Comment by christophkogler** [comment]
I believe all of the code around attractiveness of beds is working properly. 

It is simply that barracks are often more impressive than single rooms, so if you throw a bunch of beds in the barracks and one ends up being high quality, it will be picked over an unimpressive single bed room with a bad bed, even with the single bed guest room bonus. But if the highest quality guest beds are placed in the single bed rooms, they should be picked pretty much always.

**Comment by OrionFive** [comment]
Alright. Thanks. Closing this then.
