### ISSUE TITLE
Hospitality: Guests recruit prisoners to their faction

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#591]
Fix it again.

**Comment by christophkogler** [comment]
I think the problem is that InteractionWorker_RecruitAttempt DoRecruit sets the recruited to the **recruiters** faction. So a guest with WorkGiver_Warden_Convert will recruit to their faction, not the players. 
In JobGiver_Relax GetJob, you could check if the job is a PrisonerConvert job via def before returning the job, and use a guest version of both the job and interaction worker, that recruits to the player's faction specifically instead? I'm not sure how complex that would be to implement, but it seems like the simplest solution to me. The interaction worker could basically be a copy-paste with a few lines changed, to make it the player's faction always. As only guests should possibly ever run it, I don't think it could cause problems?

**Comment by OrionFive** [comment]
That's the reason, yeah. But I'm not a fan of duplicating entire jobs, that will definitely cause problems with other mods that modify recruiting prisoners.If you look at the smooth wall patch, that's the same situation and how it's usually solved.If I'm lucky, it's in a nice method that I can override or append. If I'm unlucky, it's a tangled mess of an multi-nested if statement and I have to transpile it.I haven't looked at the code yet. So who knows.

**Comment by christophkogler** [comment]
I went and looked at DoRecruit, and I think a Harmony Postfix patch similar to the smooth wall fix would work. Some of the checks in DoRecruit adjust what happens, but none end it, if that is the concern.

**Comment by OrionFive** [comment]
Sounds good. I just gotta write the patch then.

**Comment by OrionFive** [comment]
Fixed in next version, however for now I've disabled all warden jobs for guests, because many of them feel pretty weird being done by guests and some might still cause issues.
