### ISSUE TITLE
Hospitality: Incompatible with Gear Up and Go

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#596]
PathToV1ctory 1 hour ago 
Likely the same source as CE breaking was (GearUpAndGo uses pawn.thinker.TryGetMainTreeThinkNode<JobGiver_OptimizeApparel>() ), although I'm not sure how. The guest version of optimize apparel SHOULD be returning the vanilla version if called by colonists.

Orion  [author] 10 hours ago 
Sounds like some Hospitality patch is affecting it, yeah. 🤔

WIbigdog 12 hours ago 
Also whether Better Pawn Control is active or not doesn't change the end behavior when Hospitality is also installed.

WIbigdog 12 hours ago 
https://steamcommunity.com/sharedfiles/filedetails/?id=2586063299 Here's Mlie's updated mod for 1.3

WIbigdog 12 hours ago 
What happens when Hospitality is installed is that it will still change the policy from Better Pawn Control but they skip the step where they make sure their outfit matches their assigned outfit and instead are just immediately drafted and move to the spot selected. Mlie has suggested that it could be conflicting with guests trying to optimize their outfits? Specifically he said: "Hm, perhaps it tries to optimize the outfit for a hospitality guest?"

WIbigdog 12 hours ago 
So what is supposed to happen is that when you click the button that Gear Up and Go adds (With Better Pawn Control installed preferably, as it will switch their outfit automatically) they will first stop what they are doing and go change their outfit. Once their outfit is satisfied (typically armor and utility stuff) they will then be drafted and go to the spot that you sent them to. So to clarify with Better Pawn Control installed when you click the button it switches the colony policy to a preset one which changes the outfits of your pawns, say from "worker" to "soldier". Without Better Pawn Control you have to change their assigned outfit manually before using Gear Up and Go.

**Comment by christophkogler** [comment]
Gear Up and Go job driver is here: https://github.com/alextd/Rimworld-GearUpAndGo/blob/master/Source/JobDriver_GearUpAndGo.cs
It might be some problem with generating the ThinkResult when running TryIssueJobPackage on the guest version of optimize apparel? That seems the most likely to me at least, although I don't see _why_ it would be breaking. The guest version should essentially be immediately switching to the vanilla version for colonists, and that should return a valid job and ThinkResult.

**Comment by NanoTrasen-Inc** [comment]
Update: The original Gear Up and Go mod as been updated and this issue is still occurring.
I created a bug report on Gear Up and Go's page, though I'm not sure which mod is the actual cause of the issue.

https://steamcommunity.com/workshop/filedetails/discussion/1316142788/1698293703770108105/#c3040481180156958111

Just cross-linking things for completion's sake.

**Comment by Chraa88** [comment]
Got the same issue. I noticed that the debug log when Gear Up and Go is triggered printed "Non-guest {pawn} tried to optimize apparel." 
This debug message was removed in the "- Fix: Compatibility with Combat Extended's Optimize Apparel" commit (24e3b8); made about a week after the latest steam release of Hospitality.

Using the newest Hospitality.dll from the develop branch instead of the steam release one, the bug seems to be fixed. Pawns once again actually equip their gear according to their BCP assigned loadout before being drafted.

I'm not familiar enough with either mod to call it definitively, but it seems likely that the new behaviour of calling the base version in case of non-guest is better than the current relase behaviour of printing error and returning null. 

**FIX**
Should be fixed whenever a new release comes. For a fix in the meanwhile, you can download the Hospitality.dll from https://github.com/OrionFive/Hospitality/tree/develop/1.3/Assemblies and replace your local one under <steamlocation>\steamapps\workshop\content\294100\753498552\1.3\Assemblies
**edit**: this will bring some extra stuff with it, mostly a few CE compatibility changes. I have no idea in how finished a state these are. Since it's not a full release by the author, don't expect a fully polished result; my testing was only for this bug specifically

**Comment by OrionFive** [comment]
@Chraa88 Thanks for chiming in. I'll upload the latest version in the new few days.
