### ISSUE TITLE
No coming no beds

### ISSUE THREAD

**Issue by nathangur** [OrionFive/Hospitality#755]
I have no beds. I have checked the DO NOT COME IF NO BEDS mark over 20 times. But it unchecks itself. All. The time. It has never worked as far as I'm aware and just unchecks itself randomly.

**Comment by OrionFive** [comment]
That's unfortunate. Where's your log?

**Comment by nathangur** [comment]
How can I get the log?

**Comment by nathangur** [comment]
[Player.log](https://github.com/OrionFive/Hospitality/files/11455496/Player.log)

**Comment by OrionFive** [comment]
Sorry about the late reply. I didn't get a notification for some reason.

Anyway. It looks like your savegame is borked. Maybe you removed a mod, or maybe you saved after getting an error. Either way, it looks like stuff is not loading correctly. I can't find anything related to Hospitality in your log. So maybe you didn't press the beds button before saving the log.

Next time, please upload the log via HugsLib (Ctrl-F12), because the Player.log misses useful information.
