### ISSUE TITLE
Visitors with animals bug out when leaving 

### ISSUE THREAD

**Issue by OrionFive** [OrionFive/Hospitality#77]
If a mod adds animals to the trader (like TropiCKAPP Rainforest Mod) this causes issues.

**Comment by kaptain-kavern** [comment]
If there is anything I can do to help, I'm here.

**Comment by OrionFive** [comment]
Yeah visitors with animals causes problems :/

**Comment by eksynn** [comment]
i was literally about to paste this until i saw this (and 3 others with the same issue)
visitors keep spamming that they're about to leave but they don't xD i had to use the dev console in order to re-tame the animals i sold the visitor so he could actually leave

will this happen with caravans too?

**Comment by OrionFive** [comment]
No, caravans are not affected.

**Comment by OrionFive** [comment]
@eksynn: Okay, I checked. Normally visitors will not accept to buy animals. Do you use some mod that enables this?

**Comment by eksynn** [comment]
> @eksynn: Okay, I checked. Normally visitors will not accept to buy animals. Do you use some mod that enables this?

i'll be honest, i have no idea xD; i have over 200 mods - do you think you could help me recognise one that might?
here's my mods list (had to rename it to .txt since github doesn't like .xml files)
[ModsConfig.txt](https://github.com/OrionFive/Hospitality/files/2764151/ModsConfig.txt)

edit: sorry for the delay in responding, RL has been excessively crazy lately

**Comment by OrionFive** [comment]
Sorry, I don't have the time for that. Maybe you could just not sell them animals?

**Comment by OrionFive** [comment]
Okay, I fixed this now. I hope. Probably. Maybe. Just try.
