### ISSUE TITLE
Gastronomy: Refuses to serve one of my pawns

### ISSUE THREAD

**Issue by ChuckleMan** [OrionFive/Hospitality#780]
**Describe the bug**
One or both of my slaves serving colonists refuse to interact with a single pawn. They will serve all other guests/colonists, but not interact with a specific one. This happens regardless of where they are sitting, and which of my slaves are serving. This has continued for over a year ingame

**To Reproduce**
Aardvark goes to get a meal served
Sits down
Noone serves her

**Console log**
-=-=-=- Apologies - the log refused to parse to give a URL
https://pastebin.com/6qCUzbLg

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Paste it here
```

**Screenshots**
If you think it helps, add screenshots to help explain the problem.
![image](https://github.com/OrionFive/Hospitality/assets/51891881/c7f56dff-03b7-4bd4-b037-d2cefdb16040)

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by OrionFive** [comment]
I can't see any obvious reason in the log. The usual suspects for messing things up are mods throwing exceptions, though, which you have plenty in your log.
So possible candidates are: Ritual Obligation, Vanilla Genes Expanded, whatever MVCF is, Research Reinvented

It can also be that the damage is already done and your game state is broken (in this case luckily just a single pawn). 
Note that just removing these mods doesn't necessarily fix the issue and might break your game state further.

I can't find any relevant errors from Gastronomy, so my best guess is that some vanilla system is failing or it's caused by another mod tripping things up.

**Comment by Veylyn** [comment]
I realize this is a very old bug at this point, but I had this issue too, with a much smaller mod list, and I was able to fix it. Somehow using debug tools to force a mental break (just used sad wander), then having another colonist end the mental break with the Snap Out! mod (unsure if this is necessary) resolved the issue. I think I've had this happen to 2 colonists, but I don't know what the common initiation was for each. I'd guess a mental break given what fixed the issue though
