### ISSUE TITLE
10jobs 1tick bug. 

### ISSUE THREAD

**Issue by ParadoxSong** [OrionFive/Hospitality#79]
I turned on dev mode for logging errors after starting a new game with Hospitality, and everything went fine for over a year, but in this one particular instance  this error was produced: https://pastebin.com/nBRxKxiv

Here's the log. https://gist.github.com/HugsLibRecordKeeper/67cc8ababf9970d68a1e708c3450e0d5

**Comment by OrionFive** [comment]
Thanks for the thorough free report. Do you have any information about the circumstances? 

I have a hunch the latest update has caused this.

**Comment by ParadoxSong** [comment]
The bug occurs whenever Barbara who is assigned as a priority 3 negotiator improves relations with the visiting guest factions. There is one other priority 3 negotiator, but he may just be too busy to entertain the guests or such things.  It doesn't happen when Barbara is cheering up patients, having deep talks, or any such thing, only when improving relations.
I'm afraid I don't have any further information as to the circumstances around the bug. If I get a chance today, I'll play Rimworld again and see if it's only a certain faction or only with Barbara. There was a lot of 10job 1 tick bugs in the unstable version of this Alpha, so it may be out of your hands.

**Comment by OrionFive** [comment]
The thing is, myself, and most other people are not experiencing this issue. So there must be another mod or a special circumstance that triggers it.

Does it happen every single time or only occasionally? Does it take a while before it happens or is it immediately when engaging?

**Comment by ParadoxSong** [comment]
I can now confirm it only happens occasionally, regardless of whether the result is Offended or Charmed, and is not pawn specific.  I was running at 4x speed but when the game paused and the bug occurred the Charmed text and the shaking hands thought bubble were both onscreen.

**Comment by NoImageAvailable** [comment]
So after looking into it I think I tracked the source to this section of code: https://github.com/OrionFive/Hospitality/blob/develop/Source/Source/JobDriver_GuestBase.cs#L32-L33

The issue is the neither WorkGiver_Diplomat nor the JobDriver check for this beforehand, causing the job to fail whenever it hits the interact toil, then immediately start a new one. I assume [this toil](https://github.com/OrionFive/Hospitality/blob/develop/Source/Source/JobDriver_GuestImproveRelationship.cs#L14) is supposed to prevent this by waiting until the interaction timer is expired but it only checks if the negotiator can be interacted with, whereas the fail condition is for the guest.

In my test builds I managed to fix the error by uncommenting [this line](https://github.com/OrionFive/Hospitality/blob/develop/Source/Source/JobDriver_GuestImproveRelationship.cs#L20) and adding the following checks to WorkGiver_Diplomat:

```csharp
        public override bool HasJobOnThing(Pawn pawn, Thing t, bool forced = false)
        {
            var guest = t as Pawn;
            return guest != null && pawn.ShouldImproveRelationship(guest) && !guest.interactions.InteractedTooRecentlyToInteract();
        }

        public override Job JobOnThing(Pawn pawn, Thing t, bool forced = false)
        {
            Pawn targPawn = t as Pawn;
            if (targPawn == null || !pawn.ShouldImproveRelationship(targPawn) || targPawn.interactions.InteractedTooRecentlyToInteract())
            {
                return null;
            }
            return new Job(jobDef, t);
        }
```
I don't know if there was a specific reason why the interaction time toil was commented out and I didn't test beyond making reasonably sure the error was fixed, so there might be unintended behavior from this fix. If there are no issues from uncommenting the interaction time toil I can PR my changes or run a test colony with the fix first if you want.

**Comment by OrionFive** [comment]
Thanks for your help @NoImageAvailable! 

I've implemented your changes and tested it for a while and so far it seems good. I had made some changes in the meantime which I want to keep, so you can better not PR it. I'll test some more and then upload a new version of the mod.

**Comment by OrionFive** [comment]
@NoImageAvailable - btw, I was told with CE [players can order guests to empty their inventory](https://github.com/OrionFive/Hospitality/issues/56) - do you know if this is still an issue and what may cause it?

**Comment by NoImageAvailable** [comment]
That was reported to me but I was able to reproduce it with no mod besides Hospitality loaded, so not a conflict.

**Comment by OrionFive** [comment]
Yeah I had fixed it in A16. 

Hm. I'll have to see what other mod could cause it again.
